### ISSUE TITLE
verify calldata length

### ISSUE THREAD

**Issue by MrChico** [vyperlang/vyper#1730]
Vyper doesn't seem to do any verification of the calldata length currently, which can read to a whole range of problems and unintuitive behaviour. For reference, check out:

- https://github.com/ethereum/eth2.0-specs/issues/1357
- https://medium.com/golem-project/how-to-find-10m-by-just-reading-blockchain-6ae9d39fcd95
- https://github.com/ethereum/solidity/issues/2109

Expected behaviour is to REVERT if CALLDATA is smaller than expected

**Comment by charles-cooper** [comment]
this is an interesting set of behaviors. this issue is slightly related: https://github.com/ethereum/vyper/issues/1602.

so if I understand correctly, in some cases where user input is not validated, an address with fewer than 20 bytes could be input into a contract, and then following values will appear shifted in the calldata. as an example with an erc20 transfer, if the user inputs this address
```
0x12345678901234567890123456789012345678 # 19 bytes
```
then the calldata could look like
```
0x12345678901234567890123456789012345678<amount>
```

it's a bit unclear to me though how to detect that the calldata is smaller than expected. for static data it's pretty clear since the size can only be one value but for dynamic data you could still have this issue.

**Comment by jacqueswww** [comment]
Meeting Notes: Implement same checks as solidity.
