### ISSUE TITLE
raw_call returns empty calldata

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [vyperlang/vyper#1976]
### Version Information

* vyper Version (output of `vyper --version`): latest master
* OS: linux
* Python Version (output of `python --version`): 3.8

### What's your issue about?
The `raw_call` function always returns exactly `outsize` bytes, even when the actual data returned is less than this.

```python
@public
def foo() -> bool:
    return True
```

```python
@public
def call_foo(_addr: address) -> int128:
    response: bytes[64] = raw_call(_addr, method_id("foo()", bytes[4]), outsize=64)
    return len(response)
```

In this example, `call_foo` will return `64` even though the actual response from `foo` has a length of `32`.

### How can it be fixed?
In the LLL for `raw_call`, instead of copying `outsize` bytes into memory, copy the minimum of `outsize` and `RETURNDATALENGTH`.

**Comment by fubuloubu** [comment]
Little more context: if there is a call type that may or may not return a specific data type ('RETURNDATALENGTH' is either 0 or another number), because of this bug it would not be possible to differentiate between the two. With the fix in place, it would be possible to differentiate those two cases.

Breaking change
