### ISSUE TITLE
Reentrancy Bug in Market Maker Example

### ISSUE THREAD

**Issue by cbraem** [vyperlang/vyper#2014]
### What's your issue about?

The example _examples/market_maker/on_chain_market_maker.vy_ seems to have a reentrancy bug. _ethToTokens_ and _tokensToEth_ first make an external function call before they update local state variables.

The effect of this reentrancy bug is demonstrated by the following example:

- _initiate_ gets called with a `token_quantity` of 20 and `msg.value` of 100.

- Contract _a_ calls _tokensToEth_ with a `sell_quantity` of 40.
  - This contracts will send (20 * 100) / 40 = 50 back to _a_.
 	- The default function of _a_ calls now again _tokensToEth_ with a `sell_quantity` of 40.
 		- This contracts will send again 50 back to _a_.
 			- _a_ accepts now the 50 without further reentrant calls.
 			- The second send to _a_ returns.
 		- This contract updates now `totalEthQty` to 50 and `totalTokenQty` to 60.
 		- The reentrant call returns.
 	- The first send to _a_ returns.
  - This contract updates now `totalEthQty` to 50 and `totalTokenQty` to 40.

The contract has now 60 Tokens and 0 ether. Therefore, the invariant does not hold anymore and `totalEthQty` as well as `totalTokenQty` do no longer model the current state.

I assume that these examples just demonstrate what Vyper contracts can do, but I would rather suggest to fix such a reentrancy bug not to show case anti-patterns.

### How can it be fixed?
Move the call to _transfer_ at the end of _ethToTokens_ and also move _send_ at the end of _tokensToEth_.

**Comment by fubuloubu** [comment]
Yep, this appears to be true.

You suggested solution would definitely work to mitigate this, or it might also be a good spot to show off our `@nonreentrant('name')` decorator (our implementation of `OpenZeppelin/ReentrancyGuard.sol`), using the same `name` on both  `ethToTokens` and `tokensToEth` to ensure that a reentrancy guard is created for both calls when either call is made.

If you want to fix it, let me know, otherwise I'll look into making this change when I get a chance.

**Comment by cbraem** [comment]
You're right, the `nonreentrant` decorator is even a better solution.

Since I only have an already built version of vyper and don't know everything that I should consider before making a commit / pull request, I would gratefully accept your offer to make this change.

**Comment by fubuloubu** [comment]
Our test suite tests everything in `examples/`, but obviously a reentrancy test was missing. I'd first find the file (in `tests/`) where that example is being tested, add a test with a malicious contract that performs a reentrant call, and then see that adding our decorator makes it fail.

Make a PR for that, and you should be good to go!
Thanks for taking a look!

**Comment by fubuloubu** [comment]
On further inspection, this is not true, due to the 2300 gas limit on `send`, checkout:
https://github.com/vyperlang/vyper/blob/1ebce95ed4fec4d96120d93df6f347799e8c7e02/tests/parser/functions/test_send.py#L31-L72

---

It may be time to re-evaluate this mechanic, and explore using a "default reentrancy guard" on all outgoing `send`s instead (protecting against reentrancy without using a broken gas mechanic that may have a silent failure)

cc @iamdefinitelyahuman thoughts?

**Comment by iamdefinitelyahuman** [comment]
Relying on the 2300 gas sent seems bad, yeah.  And limiting the gas to 2300 is also a bit outdated and we should rethink that IMO: https://diligence.consensys.net/blog/2019/09/stop-using-soliditys-transfer-now/

I'm not sure how I feel about a default re-entrancy guard either but definitely into having a conversation about it.

**Comment by fubuloubu** [comment]
Lol, already had this discussion: #1756
