### ISSUE TITLE
line comment in last line of a function

### ISSUE THREAD

**Issue by benjyz** [vyperlang/vyper#2410]
### Version Information

* vyper Version (output of `vyper --version`):0.2.14+commit.db2606d
* OS: osx
* Python Version (output of `python --version`): 3.9.6

### What's your issue about?

if last line in a function is a comment I get this
```
x: public(uint256)

@external
def foo(ix: uint256):
    bar: uint256 = self.x
    #?? throws >> ValueError: start (7,7) precedes previous end (8,0)
```

### How can it be fixed?

no idea

**Comment by charles-cooper** [comment]
Appears https://github.com/vyperlang/vyper/issues/1161 has come back to life

**Comment by charles-cooper** [comment]
I figured out why I was not getting an error [in the previous issue](https://github.com/vyperlang/vyper/issues/1161#issuecomment-459605422). My text editor inserts a newline at the ends of files, and when the newline is there there is no issue. Here's a minimal repro:
```console
(vyper) charles@cmc-thinkpad ~/vyper $ xxd repros/2410.vy 
00000000: 2320 6661 696c                           # fail
(vyper) charles@cmc-thinkpad ~/vyper $ vyper -f ir repros/2410.vy 
ValueError: start (1,6) precedes previous end (2,0)

(vyper) charles@cmc-thinkpad ~/vyper $ vim repros/2410.vy # add newline
(vyper) charles@cmc-thinkpad ~/vyper $ xxd repros/2410.vy 
00000000: 2320 7375 6363 6573 730a                 # success.
(vyper) charles@cmc-thinkpad ~/vyper $ vyper -f ir repros/2410.vy 
seq
```

However, this should have been fixed in https://github.com/vyperlang/vyper/pull/1720 ... not sure why this is cropping up again.
