### ISSUE TITLE
Immutable variables can be read before assignment

### ISSUE THREAD

**Issue by ptrcarta** [vyperlang/vyper#3101]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.6+commit.4a2124d
* OS: osx
* Python Version: 3.9.13
 
### What's your issue about?

Immutable variables can be read before assignment, their memory location during constructor execution is accessed, but that memory is not initialized yet. Its value is not necessarily `empty(type)` since memory could have been written to ephemerally.

This should not compile:

```python
# @version 0.3.6

a:immutable(uint256)
b:uint256

@payable
@external
def __init__(s:address):
    self.b = a
    a = 12
```

A more interesting example where transient memory written during execution of `create_copy_of()` is written into the storage variable `b`:

```python
# @version 0.3.6

a:immutable(uint256)
b:uint256

@payable
@external
def __init__():
    s:address = 0x9D0464996170c6B9e75eED71c68B99dDEDf279e8  #random contract containing code that is copied to memory before redeploying
    c:address = create_copy_of(s)
    self.b = a
    a = 12
```

### How can it be fixed?

check that immutable variables are assigned before usage

**Comment by charles-cooper** [comment]
after checking this a bit more, the issue arises not because the immutables section does not start out as zeroed, but because of an interaction between `msize` and the static memory allocator. `create_copy_of` (and its sister, `create_from_blueprint`) uses `msize` to determine a starting location for where to copy the target bytecode into memory, while the immutables section start is determined using the static memory allocator. in case that msize is still less than the immutables section end, it can write to the immutables section thereby resulting in reads from the immutable section to return garbage (before the immutables have been initialized in user code).

note that variables in runtime code are not susceptible to the same issue because vyper [requires memory variables to be explicitly initialized](https://github.com/vyperlang/vyper/issues/1493), so we don't see the same interaction between the static memory allocator and `msize`.

for this issue, i think we can simply force msize to be initialized to past the end of the static memory allocator by calling `mload <static_memory_end>` before running any initcode.
