### ISSUE TITLE
EVM error OutOfGas with DynArray for loop

### ISSUE THREAD

**Issue by milkyklim** [vyperlang/vyper#3234]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.7+commit.6020b8b
* OS: osx
* Python Version (output of `python --version`): Python 3.8.6

### What's your issue about?

Vyper sample I use:

```vyper
# @version 0.3.7
MAX_NUM: public(constant(uint256)) = 10 ** 12

struct MyStruct:
    one: uint256
    two: uint256
    there: uint256

@view
@external
def get_values(n: uint256) -> DynArray[uint256, MAX_NUM]:
    _ids: DynArray[uint256, MAX_NUM] = []

    for i in range(0, MAX_NUM):
        if i >= n:
            break
        _ids.append(i)

    return _ids
```

Code compiles but when I try to call `.get_values(3)` in ape I get an error `ape.exceptions.VirtualMachineError: EVM error OutOfGas`. This can be ape error all along, will reopen there once confirmed. 

### How can it be fixed?

--

**Comment by trocher** [comment]
I believe this is happening because `i` is stored in memory after `_ids`. As `_ids` has reserved one word for its length as well as `10**12` words for its content, `i` must be stored at a very large index in the memory and hence a call to `get_values` cost excessive amount of gas.

**Comment by jaglinux** [comment]
10 ** 12 is too high. I tried with 
`MAX_NUM: public(constant(uint256)) = 100`
and it works.
Maybe range function creates the sequence of number on the fly and hence out of gas exception for bigger range values ?

**Comment by charles-cooper** [comment]
right, the issue has to do with the fact that the memory is statically allocated. do you really want to return such a large array (in the worst case)?

**Comment by jaglinux** [comment]
Right! OP is @milkyklim and can explain about return of large array.

**Comment by fubuloubu** [comment]
> 

Ahhh, okay @milkyklim this is the problem! when you try to create such a large memory array, gas usage for memory is quadratic with the number of elements! and vyper create space for that large of an array to exist.

it becomes a problem when you have a memory variable defined _after_ the array (in this case, `i` in the `range` function), because that variable gets created at position `MAX_NUM + 1` (more or less), which costs... well, over `10 ** 24` gas

**Comment by fubuloubu** [comment]
Talked more offline, a good solution here might be to create a warning when a dynarray would create memory expansion that costs more than a specific amount, say 1m gas units, and suggest that the user reduce the size of the array, or make it the last item in memory so that the expansion doesn't take affect (unless you use it)

**Comment by charles-cooper** [comment]
> Talked more offline, a good solution here might be to create a warning when a dynarray would create memory expansion that costs more than a specific amount, say 1m gas units, and suggest that the user reduce the size of the array, or make it the last item in memory so that the expansion doesn't take affect (unless you use it)

yea i was going to mention this -- going to close this issue and create a new issue to track the warning
