### ISSUE TITLE
Unable to reproduce bytecode between contract generated from docker and binary

### ISSUE THREAD

**Issue by Enigmatic331** [vyperlang/vyper#3369]
File in question: https://gist.github.com/Enigmatic331/5d85f73ec4b8e85ace1a2fa36c86790f

It seems that we are having issues reproducing the same bytecode for this contract when compiling between using the Vyper binaries and docker instances...

Compiled from vyper 0.3.7 binaries `vyper037.exe CurveTricryptoOptimizedWETH.vy -f bytecode > output_037.txt`, results are as such: https://gist.github.com/Enigmatic331/c58aeafd6a3a36f9791b22b4098aff43

Compiled from vyper 0.3.7 docker, `docker run vyperlang/vyper:0.3.7 /code/CurveTricryptoOptimizedWETH.vy -f "bytecode" > docker_output_037.txt`, results are as such: https://gist.github.com/Enigmatic331/085372a589a8509483b67b2977d6909d

Running the diffs: https://difff.jp/en/9bis6.html

Not sure if I might be missing anything - Since on both cases am compiling the contract without additional settings except to output "bytecode"..... Any idea what I might be missing? 🙏

**Comment by Enigmatic331** [comment]
There is also an issue where we intermittently end up generating different bytecodes with minor differences (e.g. attached three outputs, all compiled using vyper037.exe CurveTricryptoOptimizedWETH.vy -f bytecode > filename) - Though I reckon this is secondary and resolving diffs between docker <> binary would also sort this out....


[output_117PM.txt](https://github.com/vyperlang/vyper/files/11331731/output_117PM.txt)
[output_118PM.txt](https://github.com/vyperlang/vyper/files/11331730/output_118PM.txt)
[output_121PM.txt](https://github.com/vyperlang/vyper/files/11331729/output_121PM.txt)

**Comment by pcaversaccio** [comment]
I replicated the following behavior:

```
yolo:~$ docker run vyperlang/vyper:0.3.7
yolo:~$ docker run vyperlang/vyper:0.3.7 /src/tokens/WETH.vy -f "bytecode" > docker_output_037.txt
```

[docker_output_037.txt](https://github.com/vyperlang/vyper/files/11333647/docker_output_037.txt)

Left is binary and right is docker output: https://difff.jp/en/33ari.html

I don't have the same diffs as Etherscan (very weird) but there are some diffs. I used the same contract but just renamed it to `WETH.vy`.

**Comment by charles-cooper** [comment]
been digging into this -- apparently, the topsort order for function codegen is not stable. the underlying reason for this seems to be, while `dict` objects guarantee insertion order since python 3.7, [`set` makes no such guarantee](https://groups.google.com/g/dev-python/c/QYwuyo_qQRE), and sets are used in computing the call graph as of 4b44ee7bcc3d9dba74329cf35436a267e4dafa8: https://github.com/vyperlang/vyper/blob/4b44ee7bcc3d9dba74329cf35436a267e4dafa87/vyper/semantics/types/function.py#L126

it might be possible to force the insertion order to be stable by fixing `PYTHONHASHSEED`, but the underlying fix will be to replace any uses of `set` with `OrderedSet`.

**Comment by Enigmatic331** [comment]
Thank youuuu Charrleeesss aaaaaaaaa ❤️ 

Yea I would reckon [setting PYTHONHASHSEED helps](https://stackoverflow.com/questions/3812429/is-pythons-set-stable) - Though a quick run yesterday by setting it on our Environment Variables didn't seem to generate a stable bytecode across two machines (despite during python runtime print(os.environ["PYTHONHASHSEED"] showed 0) - Not too sure what's the deal with that but we will be digging around this a bit more.

**Comment by c-protocol-team** [comment]
Thank you very much indeed, Charles. Please note that until a new version of the compiler is released source verification on etherscan of some vyper contracts will continue to fail.

**Comment by banteg** [comment]
For anyone landing here with an already-deployed 0.3.4–0.3.7 contract that won't verify: this is now solvable with stock compilers, no forks.

A few findings from digging into it (full writeup: https://banteg.xyz/posts/vysort/):

- `PYTHONHASHSEED` does nothing because the dice aren't string hashing — `called_functions` is a plain `set()` of objects with no `__hash__`, so iteration order comes from `id()`, i.e. heap layout. The official PyInstaller binaries are nondeterministic *run to run*; pip installs differ per python version.
- The nondeterminism only manifests at a *decision point*: a `called_functions` set holding ≥2 internal functions not yet placed when the topsort DFS reaches it. Internals defined before their callers are placed by the outer source-order loop first, so ~93% of affected-band mainnet contracts have exactly one reachable layout and were never at risk — that's why most contracts verify on the first try.
- The same rule is the antidote: move the internal function defs to the front of the file in the deployed order and the topsort has zero decision points — any stock 0.3.x compiler then reproduces the deployed bytecode deterministically, every run. The deployed order itself can be decoded straight off the on-chain bytecode in one instrumented compile (no permutation search).

Packaged as a tool: https://github.com/banteg/vysort — `uvx vysort verify Contract.vy --address 0x... --rpc-url ...` decodes the layout, rewrites the source, and submits to sourcify through the standard flow. Validated against every at-risk source-available mainnet runtime (26/26 byte-exact modulo immutable tails), including a 23-internal-function contract with a ~10⁴⁹ ordering space.

Verifier-side discussion: https://github.com/argotorg/sourcify/issues/2825
