### ISSUE TITLE
VIP: Package Management via EthPM

### ISSUE THREAD

**Issue by VoR0220** [vyperlang/vyper#483]
#### Simple Summary

We need package management integration like people expect in the modern age of programming. 

#### Motivation

One of the biggest pitfalls of Solidity as a language has been the lack of a package manager built into the language. Today, Golang has Dep, Rust has Cargo, Node has NPM, Python has Pip. Viper needs to cater to the needs of novice programmers and this is something that truly helps the development process.

#### Specification

Fortunately, a [spec already exists](https://github.com/ethpm/ethpm-spec) and it's made to be compatible with other languages such as Solidity! We just need to build it in to follow the ethPm specification, perhaps carving out a slice of itself for Viper. 

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/7756785/32985284-050f1eb8-cc7d-11e7-812d-7b25ce4e333c.png)

**Comment by daniel-jozsef** [comment]
How exactly do you envision packages to work in a language that does not have inheritance or local libraries?

(I'm not being snarky, it's an actual thing we should think about. Code reusability vs. readability. Generally, a single Viper contract should be a single file in the end. However, I don't see it as entirely sacrilegious to have some kind of cut-and-paste preprocessor that generates an "auditor view" file from a set of "programmer view" files. Then, the Viper compiler would compile the "auditor view", ie. single file contract into EVM bytecode.)

**Comment by fubuloubu** [comment]
I've been suspect of the whole PM approach myself for this reason. When code is this expensive to get wrong and is this high level (so there is no reason to have a smart contract more than a few hundred lines tops), I prefer if you went through the effort of manually copying successful implementations instead of basing your code on libraries or classes from others. This limits the attack vectors available from external sources and has the added benefit of forcing you to understand your code enough to copy and paste it successfully.

We are planning on having the viper compiler define built-in macros for extensively proven use cases in order to make writing code easier for Viper developers. These macros will generate more basic syntax (sort of like preprocessor macros) so that the code you would make publicly available is is easily auditable as possible (everything all in one place).

90% of smart contract work will be understanding and testing the code, I'd say focus on making that easier first. (or better yet creating a PM system that integrates testing easily with the underlying code modules easily)

**Comment by VoR0220** [comment]
@fubuloubu there's plenty of reason to use a package manager here. Linking to other code already on the chain (makes deployment cheaper), reduction of redundancies on the chain with libraries (makes miners have to retain less state), and bringing in audited utilities (ala OpenZeppelin or Dapphub) are an excellent usecase for package management.

**Comment by fubuloubu** [comment]
[Counter-argument](https://www.theregister.co.uk/2017/11/07/parity_wallet_destroys_280m_ethereum/) to that counter-argument (about leveraging more on-chain code)

Until we can deploy bug-free code, I still don't think it's the best idea to link everything together. If the parity "library" were deployed inside every wallet contract, this never would have been as big an issue because the researcher would only have locked out one wallet.

There are pros and cons to that approach, but until we have bug-free code, a means to universally identify code hardiness, or some sort of code "insurance", I'd rather make it more difficult to deploy code that you don't fully understand. That's why I disagree that PM is a "must have" vs. a useful tool for experienced developers to reduce work.

**Comment by fubuloubu** [comment]
To expand on "universally identify code hardiness", let me explain myself a bit: I used to work for an aerospace company where we followed DO-178B in order to qualify our software for flight. If I had a piece of software that was qualified to the Level A spec, that means there was a decent amount of "trust" that the software went through adequate testing to ensure it did what it said it did, and didn't have catastrophic bugs. It's not a guarantee however, so any software that had actually been in flight test or production for a fair amount of time had extra confidence because it survived "in the wild". The longer it spent in flight test or production, the more it could be trusted because it was being used for it's intended purpose. NASA has a related metric called the TRL which puts objective measurements on the amount of use a piece of software has. A TRL9 means it has been on multiple missions (used for it's intended purpose for many hours of mission time) and therefore can be trusted to be reused again with minimal impact.

Not to say that Aerospace and Smart Contracts are the same thing. Smart Contracts will be used in a much more commercial setting on the web by many thousands of users, and additionally have to deal with malicious actors who wish to game the rules specified in the contracts. If a Package Management system took all this into account, I would be much happier to enable it in this language. By that point hopefully Viper is something mainstream and this approach would make a lot of sense.

I hope you understand where I'm coming from on this a little better now.

**Comment by daniel-jozsef** [comment]
I have created a VIP specifically about how we could in theory preserve the no-compositon value of Viper (it's a feature, not a bug), while also allowing reusable code. [https://github.com/ethereum/viper/issues/584]

Still, for now, I'm definitely agreeing with @fubuloubu about manual copy-paste being the safest bet for now. Smart contracts are _not_ generic software development, the less similar it feels, the more we can get people to actually pay attention.

**Comment by fubuloubu** [comment]
@jacqueswww Is this deprecated by a more recent VIP?

**Comment by fubuloubu** [comment]
This is no longer something considered for use in the compiler itself, but frameworks such as Brownie can make integrations for package management, using Vyper's API for contract interfaces:
https://eth-brownie.readthedocs.io/en/stable/ethpm.html
