### ISSUE TITLE
FAQs - what would you like to see included there

### ISSUE THREAD

**Issue by MadelineAu** [vyperlang/vyper#944]
I've started writing up some FAQs to include in the docs.  I've got some ideas about what to start with and will look through the Issues here and gitter to see what else is coming up regularly.  But would love to hear any suggestions for what you'd like included or where else I should be looking. 

Thanks 
Madeline

**Comment by fubuloubu** [comment]
Q: Is Vyper going to be the new hotness and kill Solidity forever and ever?
A: No. Solidity will always be an option as long as it continues to be supported

Q: Should I use Vyper to hold lots of funds?
A: Not yet, test small

Q: Vyper should have assembly (note: this is not a question)
A: No, you're wrong

**Comment by MadelineAu** [comment]
On the first one, from what I've read, they're targeted at slightly different purposes.  I think the example of medical records and the need for absolute security was given as an example of where Vyper would be better than Solidity.  But are there examples where security is not hugely important?

**Comment by fubuloubu** [comment]
> are there examples where security is not hugely important?

Scam games.

I don't think that's the right distinction to draw. Solidity is simply more powerful. It allows bigger user cases and bigger apps. We only aim to be the 80% solution. Most projects will be able to choose between Solidity and Vyper, after accepting the limitations we place on them over what is acheiveable on Solidity. There is only a small subset of use cases where Vyper is not sufficient to implement.

Otherwise, it comes down to personal preference. This is a good thing, multiple compilers are like multiple full nodes: having a bug in one of them is really bad but not completely catastrophic (as long as both are used about equally)

**Comment by iamdefinitelyahuman** [comment]
Closing as stale.
